name: Day4-Branch&Path Rule
on:
    push:
        branches:
            - main
            - 'release/*'
        paths:
            - '**/*.py' # 只有 Python 文件变更才触发
            - '!docs/**' # 排除 docs 目录
    pull_request:
        branches:
            - main
            - 'release/*'
        paths:
            - '**/*.py'
            - '!docs/**'
    workflow_dispatch: # 手动触发兜底

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            APP_ENV: dev
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
                cache: 'pip'
            - name: Install deps
              run: |
                python -m pip install --upgrade pip
                if [-f requiremnts.txt];then pip install -r requirements.txt; fi
            - name: Show env
              run: |
                echo "APP_EVN = ${APP_EVN}"
            - name: Run tests
              run: pytest -q



