name: CI - TEST on main
on:
    push:
        branches:
            - main
        paths:
            - '**/*.py' # 只有 Python 文件变更才触发
            - '!docs/**' # 排除 docs 目录
    pull_request:
        branches:
            - main
        paths:
            - '**/*.py'
            - '!docs/**'
    workflow_dispatch: # 手动触发兜底
concurrency:
  group: ci-main-${{github.ref}}
  cancel-in-progress: true
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            APP_ENV: dev
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.10'
                cache: 'pip'
            - name: Install deps
              run: |
                python -m pip install --upgrade pip
                if [-f requiremnts.txt];then pip install -r requirements.txt; fi
            - name: Show env
              run: |
                echo "APP_ENV = ${APP_ENV}"
            - name: Run tests
              run: pytest -q
            - name: Upload junit
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: junit-report
                path: reports/junit.xml